name: 'Release'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - matejaVuradin/semanticPR_CI_Release
jobs:
  maybe-release:
    name: release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{secrets.PERSONAL_TOKEN}}
          default-branch: master
          release-type: node
          monorepo-tags: true
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"revert","hidden":true}]'

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}

      - run: corepack enable
        if: ${{ steps.release.outputs.releases_created }}

      - run: yarn install --immutable
        if: ${{ steps.release.outputs.releases_created }}

      - run: yarn build
        if: ${{ steps.release.outputs.releases_created }}

      - env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
          
      - run: yarn npm publish --tolerate-republish --access public
        if: ${{ steps.release.outputs.releases_created }}

  page:
      name: Cloudflare Pages
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            cache: yarn
            node-version: '18'
        - run: corepack enable
        - name: Install
          run: yarn install --immutable
        - name: Build
          run: yarn build:storybook
        - name: Publish to Cloudflare Pages
          uses: cloudflare/pages-action@v1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: 2238a825c5aca59233eab1f221f7aefb
            projectName: "matejaweb"
            directory: ./storybook-static
            gitHubToken: ${{ secrets.PERSONAL_TOKEN }}
            branch: ${{ github.head_ref || github.ref_name }}